### ISSUE TITLE
Failed to load jshint library

### ISSUE THREAD

**Issue by adriatic** [adriatic/remix-feedback#1]
This is just the beginning of errors written to VSCode output, as the consequence of running the following commands
```
npm install react react-dom react-router-dom
npm install --save-dev @remix-run/dev
```
There were no error indications on the terminal window of VSCode.

```
[Error - 4:14:05 PM] Failed to load jshint library
(node:4990) UnhandledPromiseRejectionWarning: Error: Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then reload.
    at Linter.<anonymous> (/Users/nikolajivancic/.vscode/extensions/dbaeumer.jshint-0.11.0/jshint-server/out/server.js:336:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/nikolajivancic/.vscode/extensions/dbaeumer.jshint-0.11.0/jshint-server/out/server.js:9:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `Code Helper (Renderer) --trace-warnings ...` to show where the warning was created)
(node:4990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4990) UnhandledPromiseRejectionWarning: Error: Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then reload.
    at Linter.<anonymous> (/Users/nikolajivancic/.vscode/extensions/dbaeumer.jshint-0.11.0/jshint-server/out/server.js:336:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/nikolajivancic/.vscode/extensions/dbaeumer.jshint-0.11.0/jshint-server/out/server.js:9:65)
```

After installing jshint by running `npm install -g jshint` this problem disappeared.

**Comment by jacob-ebey** [comment]
This doesn't seem to be Remix, but rather a VSCode plugin you have installed that is trying to load the `jshint` library, specifically this plugin: https://marketplace.visualstudio.com/items?itemName=dbaeumer.jshint

**Comment by adriatic** [comment]
Yes, I guessed that - however based on the number of people that were / are following Kent's course https://epicreact.dev the Remix documentation should state to remove `jshint` library (as they will all get trapped in this)
