### ISSUE TITLE
command not found: remix

### ISSUE THREAD

**Issue by adriatic** [adriatic/remix-feedback#2]
Tried to run the [Installing Remix](https://docs.remix.run/v0.21/tutorial/1-installation/#installation) sample:
```
npx create-remix@latest
cd my-remix-app
remix dev
```
This resulted with the following file structure (as rendered with VSCode

![image](https://user-images.githubusercontent.com/2712405/142525480-cfc3e829-8e3b-4a8a-a5f2-50f5bb46eb26.png)

The context for execution is not set correctly as shown below

```
~ remix dev
zsh: command not found: remix
```

Tried also this 
```
> start
> remix-serve build

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/nikolajivancic/work/learning/remix/try-2/y/build'
Require stack:
- /Users/nikolajivancic/work/learning/remix/try-2/y/node_modules/@remix-run/serve/index.js
- /Users/nikolajivancic/work/learning/remix/try-2/y/node_modules/@remix-run/serve/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.createApp (/Users/nikolajivancic/work/learning/remix/try-2/y/node_modules/@remix-run/serve/index.js:35:12)
    at Object.<anonymous> (/Users/nikolajivancic/work/learning/remix/try-2/y/node_modules/@remix-run/serve/cli.js:31:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nikolajivancic/work/learning/remix/try-2/y/node_modules/@remix-run/serve/index.js',
    '/Users/nikolajivancic/work/learning/remix/try-2/y/node_modules/@remix-run/serve/cli.js'
  ]
}
```
**Note** the name of the created application is set to Y - this name is derived from my answer Y to the question whether the  generated app should be **`my-remix-app`**

**Comment by jacob-ebey** [comment]
Ah, NPM doesn't auto link "binaries" for you. We have the NPM scripts in "package.json" for you that run the remix commands. You should start / build your app with the following commands:

Development Server: `npm run dev`
Build: `npm run build`
Start: `npm run start`

**Comment by adriatic** [comment]
I did figure this out, however, I wanted to report it to indicate the that the documentation needs this correction. You might point people at your [README.md](https://github.com/jacob-ebey/ebey-me-remix#welcome-to-remix), until such documentation details get fully polished.
